-- seed.sql
-- Auto-generated seed data for Shubham Art Online Store

BEGIN;

-- Disable triggers during seed to bypass auth-based checks.
SET session_replication_role = replica;

-- Clear existing data to make seeding repeatable
TRUNCATE public.offer_products, public.offer_categories, public.product_variants, public.custom_options, public.product_media, public.products, public.categories, public.offers, public.site_settings, public.testimonials, public.audit_logs CASCADE;

-- =========================================================================
-- 1. INSERT CATEGORIES
-- =========================================================================
INSERT INTO public.categories (id, name, slug, description, image_url, display_order, is_active) VALUES ('9df89dd9-ffcd-42bb-9ce9-75dba3cc5bfa', 'Brand Showcase', 'brand-showcase', 'Handcrafted Brand Showcase and personalized art pieces.', NULL, 1, true);
INSERT INTO public.categories (id, name, slug, description, image_url, display_order, is_active) VALUES ('a54663f6-2941-43a9-a526-ddb81190df21', 'Business Signage & Letters', 'business-signage-letters', 'Handcrafted Business Signage & Letters and personalized art pieces.', NULL, 2, true);
INSERT INTO public.categories (id, name, slug, description, image_url, display_order, is_active) VALUES ('6f67c3f3-23c3-4f0f-9ce2-b81fb24e429b', 'Custom Keychains', 'custom-keychains', 'Handcrafted Custom Keychains and personalized art pieces.', NULL, 3, true);
INSERT INTO public.categories (id, name, slug, description, image_url, display_order, is_active) VALUES ('762b098d-4ebd-4fe5-bdc1-5d9eb9dbdfbf', 'Desk Organizers & Stands', 'desk-organizers-stands', 'Handcrafted Desk Organizers & Stands and personalized art pieces.', NULL, 4, true);
INSERT INTO public.categories (id, name, slug, description, image_url, display_order, is_active) VALUES ('c2019c04-21df-4ac1-9493-4e5d8f6eb6d3', 'Drinkware', 'drinkware', 'Handcrafted Drinkware and personalized art pieces.', NULL, 5, true);
INSERT INTO public.categories (id, name, slug, description, image_url, display_order, is_active) VALUES ('43f86136-c0d7-40b8-a49e-3aad3fe1ad28', 'Jewelry & Accessories', 'jewelry-accessories', 'Handcrafted Jewelry & Accessories and personalized art pieces.', NULL, 6, true);
INSERT INTO public.categories (id, name, slug, description, image_url, display_order, is_active) VALUES ('93d59815-87b9-4a3f-b0e4-a3b59b63d9c9', 'Leather Diaries & Notebooks', 'leather-diaries-notebooks', 'Handcrafted Leather Diaries & Notebooks and personalized art pieces.', NULL, 7, true);
INSERT INTO public.categories (id, name, slug, description, image_url, display_order, is_active) VALUES ('d874298a-8c26-444b-9f08-b5ce90d7444c', 'Pet Accessories', 'pet-accessories', 'Handcrafted Pet Accessories and personalized art pieces.', NULL, 8, true);
INSERT INTO public.categories (id, name, slug, description, image_url, display_order, is_active) VALUES ('a845de12-2673-4fe9-ae01-96e498d29091', 'Trophies & Mementos', 'trophies-mementos', 'Handcrafted Trophies & Mementos and personalized art pieces.', NULL, 9, true);
INSERT INTO public.categories (id, name, slug, description, image_url, display_order, is_active) VALUES ('1dfa9b3b-c736-4c9b-a09a-cf0323510ec2', 'UV Prints & Photo Plaques', 'uv-prints-photo-plaques', 'Handcrafted UV Prints & Photo Plaques and personalized art pieces.', NULL, 10, true);
INSERT INTO public.categories (id, name, slug, description, image_url, display_order, is_active) VALUES ('d86e9fbe-11a8-473d-8d84-508660843929', 'Wall Art & Nameplates', 'wall-art-nameplates', 'Handcrafted Wall Art & Nameplates and personalized art pieces.', NULL, 11, true);
INSERT INTO public.categories (id, name, slug, description, image_url, display_order, is_active) VALUES ('3d32729c-0589-4aef-9e3e-99a3e21f1185', 'Writing Instruments', 'writing-instruments', 'Handcrafted Writing Instruments and personalized art pieces.', NULL, 12, true);

-- =========================================================================
-- 2. INSERT PRODUCTS, MEDIA, AND OPTIONS
-- =========================================================================
-- Product: Custom Engraved Metal Name Keychain
INSERT INTO public.products (id, title, slug, short_description, description, category_id, base_price, currency, status, is_featured, is_customizable, estimated_delivery_days, material, color_theme, seo_title, seo_description, created_at, updated_at) VALUES ('1f5138bf-a329-4be9-a355-5520b9a68c30', 'Custom Engraved Metal Name Keychain', 'custom-engraved-metal-name-keychain', 'High-quality, polished steel or brass metal keychain customized with your name in beautiful Devanagari calligraphy or English script. Laser-cut to pre...', 'High-quality, polished steel or brass metal keychain customized with your name in beautiful Devanagari calligraphy or English script. Laser-cut to precision, offering a glossy and premium finish. Ideal for keys, backpacks, and personal gifting.', '6f67c3f3-23c3-4f0f-9ce2-b81fb24e429b', 199, 'INR', 'custom_order', false, True, 7, 'Metal', 'Rose Gold', 'Custom Engraved Metal Name Keychain', 'High-quality, polished steel or brass metal keychain customized with your name in beautiful Devanagari calligraphy or English script. Laser-cut to pre...', now(), now());
  INSERT INTO public.product_media (id, product_id, media_url, media_type, alt_text, display_order, is_primary)   VALUES ('0d8c5245-d10d-48e1-83d1-aaf5f9c54b39', '1f5138bf-a329-4be9-a355-5520b9a68c30', 'SA001_main.jpg', 'image', 'Custom Engraved Metal Name Keychain Image 1', 0, true);
  INSERT INTO public.product_media (id, product_id, media_url, media_type, alt_text, display_order, is_primary)   VALUES ('29d4a921-c89f-405a-824e-98e7dc178f30', '1f5138bf-a329-4be9-a355-5520b9a68c30', 'SA015_main.jpg', 'image', 'Custom Engraved Metal Name Keychain Image 2', 1, false);
  INSERT INTO public.product_media (id, product_id, media_url, media_type, alt_text, display_order, is_primary)   VALUES ('2ac08f54-3500-4727-bd8b-e1259aa6b68f', '1f5138bf-a329-4be9-a355-5520b9a68c30', 'SA021_main.jpg', 'image', 'Custom Engraved Metal Name Keychain Image 3', 2, false);
  INSERT INTO public.product_media (id, product_id, media_url, media_type, alt_text, display_order, is_primary)   VALUES ('d45fe136-e486-4c49-bad3-3d8a9a19d1d8', '1f5138bf-a329-4be9-a355-5520b9a68c30', 'SA023_main.jpg', 'image', 'Custom Engraved Metal Name Keychain Image 4', 3, false);
  INSERT INTO public.product_media (id, product_id, media_url, media_type, alt_text, display_order, is_primary)   VALUES ('453cd868-b0c6-4fdd-9fe2-d89d3818f296', '1f5138bf-a329-4be9-a355-5520b9a68c30', 'SA033_main.jpg', 'image', 'Custom Engraved Metal Name Keychain Image 5', 4, false);
  INSERT INTO public.product_media (id, product_id, media_url, media_type, alt_text, display_order, is_primary)   VALUES ('21aa72b0-fc71-4a71-ad3d-170b004d0c6a', '1f5138bf-a329-4be9-a355-5520b9a68c30', 'SA062_main.jpg', 'image', 'Custom Engraved Metal Name Keychain Image 6', 5, false);
  INSERT INTO public.custom_options (id, product_id, label, input_type, required, options, display_order, is_active)   VALUES ('4fc2f339-afa7-4f45-b0ac-2a7854b824ba', '1f5138bf-a329-4be9-a355-5520b9a68c30', 'Custom Name / Text', 'text', true, NULL, 0, true);
  INSERT INTO public.custom_options (id, product_id, label, input_type, required, options, display_order, is_active)   VALUES ('c6afdb9a-1d09-4dda-8cbc-17e72bc9cd5b', '1f5138bf-a329-4be9-a355-5520b9a68c30', 'Font Style / Language', 'dropdown', true, '["Devanagari Calligraphy", "English Script", "Standard Bold"]'::jsonb, 1, true);
  INSERT INTO public.custom_options (id, product_id, label, input_type, required, options, display_order, is_active)   VALUES ('2d548068-899e-4efc-b48f-1180c39d01d7', '1f5138bf-a329-4be9-a355-5520b9a68c30', 'Material / Finish', 'dropdown', true, '["Glossy Steel", "Rose Gold Titanium", "Matte Black Metal"]'::jsonb, 2, true);

-- Product: Custom Vehicle Number Plate Keychain
INSERT INTO public.products (id, title, slug, short_description, description, category_id, base_price, currency, status, is_featured, is_customizable, estimated_delivery_days, material, color_theme, seo_title, seo_description, created_at, updated_at) VALUES ('5953c8ec-5815-4735-aa51-dd196546ba92', 'Custom Vehicle Number Plate Keychain', 'custom-vehicle-number-plate-keychain', 'Personalized mini vehicle license plate keychain designed to match your bike or car number plate. Laser-engraved for durability and long-lasting quali...', 'Personalized mini vehicle license plate keychain designed to match your bike or car number plate. Laser-engraved for durability and long-lasting quality. A perfect gift for automobile enthusiasts.', '6f67c3f3-23c3-4f0f-9ce2-b81fb24e429b', 149, 'INR', 'custom_order', false, True, 7, 'Acrylic', 'White and Black', 'Custom Vehicle Number Plate Keychain', 'Personalized mini vehicle license plate keychain designed to match your bike or car number plate. Laser-engraved for durability and long-lasting quali...', now(), now());
  INSERT INTO public.product_media (id, product_id, media_url, media_type, alt_text, display_order, is_primary)   VALUES ('8dcd2c34-54f3-4e5c-be40-fdb2d926f6b5', '5953c8ec-5815-4735-aa51-dd196546ba92', 'SA009_main.jpg', 'image', 'Custom Vehicle Number Plate Keychain Image 1', 0, true);
  INSERT INTO public.product_media (id, product_id, media_url, media_type, alt_text, display_order, is_primary)   VALUES ('402c8c5c-fc80-457c-a084-e5b394ae7235', '5953c8ec-5815-4735-aa51-dd196546ba92', 'SA043_main.jpg', 'image', 'Custom Vehicle Number Plate Keychain Image 2', 1, false);
  INSERT INTO public.custom_options (id, product_id, label, input_type, required, options, display_order, is_active)   VALUES ('3445d4a9-a47f-4624-9070-3e3dc29b9049', '5953c8ec-5815-4735-aa51-dd196546ba92', 'Vehicle Number / Text', 'text', true, NULL, 0, true);
  INSERT INTO public.custom_options (id, product_id, label, input_type, required, options, display_order, is_active)   VALUES ('fe7385ce-fc65-46c8-89ce-05fabb6db859', '5953c8ec-5815-4735-aa51-dd196546ba92', 'Design Type', 'dropdown', true, '["Standard Car Plate", "Standard Bike Plate", "Custom Font Layout"]'::jsonb, 1, true);

-- Product: Custom Acrylic Keychain
INSERT INTO public.products (id, title, slug, short_description, description, category_id, base_price, currency, status, is_featured, is_customizable, estimated_delivery_days, material, color_theme, seo_title, seo_description, created_at, updated_at) VALUES ('107b7fb9-09ec-4bba-a14e-bccebd67e36b', 'Custom Acrylic Keychain', 'custom-acrylic-keychain', 'Vibrant, lightweight, and durable custom acrylic keychains. Can be printed with company logos, custom graphics, or personalized text. Perfect for corp...', 'Vibrant, lightweight, and durable custom acrylic keychains. Can be printed with company logos, custom graphics, or personalized text. Perfect for corporate promotions, branding, or bulk gifting.', '6f67c3f3-23c3-4f0f-9ce2-b81fb24e429b', 99, 'INR', 'custom_order', false, True, 7, 'Acrylic', 'Black', 'Custom Acrylic Keychain', 'Vibrant, lightweight, and durable custom acrylic keychains. Can be printed with company logos, custom graphics, or personalized text. Perfect for corp...', now(), now());
  INSERT INTO public.product_media (id, product_id, media_url, media_type, alt_text, display_order, is_primary)   VALUES ('453b097a-4627-4e40-a582-33745ef78f69', '107b7fb9-09ec-4bba-a14e-bccebd67e36b', 'SA053_main.jpg', 'image', 'Custom Acrylic Keychain Image 1', 0, true);
  INSERT INTO public.custom_options (id, product_id, label, input_type, required, options, display_order, is_active)   VALUES ('190cc0f7-71fd-4c83-b3bc-0d8449e694e8', '107b7fb9-09ec-4bba-a14e-bccebd67e36b', 'Custom Text / Logo Upload', 'text', true, NULL, 0, true);
  INSERT INTO public.custom_options (id, product_id, label, input_type, required, options, display_order, is_active)   VALUES ('c605c33d-721e-438a-b12e-d96113e1d31f', '107b7fb9-09ec-4bba-a14e-bccebd67e36b', 'Acrylic Type', 'dropdown', true, '["Clear Acrylic", "Black Acrylic", "White Acrylic"]'::jsonb, 1, true);

-- Product: Custom Acrylic LED Backlit Nameplate
INSERT INTO public.products (id, title, slug, short_description, description, category_id, base_price, currency, status, is_featured, is_customizable, estimated_delivery_days, material, color_theme, seo_title, seo_description, created_at, updated_at) VALUES ('bfcef974-8fb0-485a-bd5b-c28565fdf7b5', 'Custom Acrylic LED Backlit Nameplate', 'custom-acrylic-led-backlit-nameplate', 'Premium illuminated house or office nameplate. Made with durable acrylic and backlit with high-quality, long-lasting LED lights. Weatherproof and idea...', 'Premium illuminated house or office nameplate. Made with durable acrylic and backlit with high-quality, long-lasting LED lights. Weatherproof and ideal for outdoor or indoor placement. Creates a beautiful glowing effect at night.', 'd86e9fbe-11a8-473d-8d84-508660843929', 1499, 'INR', 'custom_order', false, True, 7, 'Acrylic', 'Blue', 'Custom Acrylic LED Backlit Nameplate', 'Premium illuminated house or office nameplate. Made with durable acrylic and backlit with high-quality, long-lasting LED lights. Weatherproof and idea...', now(), now());
  INSERT INTO public.product_media (id, product_id, media_url, media_type, alt_text, display_order, is_primary)   VALUES ('924d7600-8a1e-4a7e-88f6-f657bc28ac19', 'bfcef974-8fb0-485a-bd5b-c28565fdf7b5', 'SA018_main.jpg', 'image', 'Custom Acrylic LED Backlit Nameplate Image 1', 0, true);
  INSERT INTO public.product_media (id, product_id, media_url, media_type, alt_text, display_order, is_primary)   VALUES ('b6ac2842-4894-41fd-b07b-de4b842b1084', 'bfcef974-8fb0-485a-bd5b-c28565fdf7b5', 'SA058_main.jpg', 'image', 'Custom Acrylic LED Backlit Nameplate Image 2', 1, false);
  INSERT INTO public.custom_options (id, product_id, label, input_type, required, options, display_order, is_active)   VALUES ('140cb402-44b3-4562-8e64-46d22c19ab23', 'bfcef974-8fb0-485a-bd5b-c28565fdf7b5', 'Name(s) to Display', 'text', true, NULL, 0, true);
  INSERT INTO public.custom_options (id, product_id, label, input_type, required, options, display_order, is_active)   VALUES ('d3dcc6fd-d307-46de-841a-a8d739d96ab6', 'bfcef974-8fb0-485a-bd5b-c28565fdf7b5', 'LED Light Color', 'dropdown', true, '["Warm White", "Cool White", "Vibrant Blue", "RGB Multi-color (with remote)"]'::jsonb, 1, true);
  INSERT INTO public.custom_options (id, product_id, label, input_type, required, options, display_order, is_active)   VALUES ('bdf3a878-07a8-4074-adef-59074a7c94ed', 'bfcef974-8fb0-485a-bd5b-c28565fdf7b5', 'Backing Board Material', 'dropdown', true, '["Black Gloss Acrylic", "Wooden Finish ACP", "Transparent Acrylic"]'::jsonb, 2, true);

-- Product: Personalized Door Nameplate
INSERT INTO public.products (id, title, slug, short_description, description, category_id, base_price, currency, status, is_featured, is_customizable, estimated_delivery_days, material, color_theme, seo_title, seo_description, created_at, updated_at) VALUES ('6d9521dd-6a74-4152-a4ad-213c8387d760', 'Personalized Door Nameplate', 'personalized-door-nameplate', 'Elegant, non-illuminated nameplate for homes, bungalows, or offices. Features custom fonts, laser-cut letters, and high-quality finishes (wood, acryli...', 'Elegant, non-illuminated nameplate for homes, bungalows, or offices. Features custom fonts, laser-cut letters, and high-quality finishes (wood, acrylic, or composite materials) that add an inviting touch to your entrance.', 'd86e9fbe-11a8-473d-8d84-508660843929', 799, 'INR', 'custom_order', false, True, 7, 'Acrylic', 'Customized Color', 'Personalized Door Nameplate', 'Elegant, non-illuminated nameplate for homes, bungalows, or offices. Features custom fonts, laser-cut letters, and high-quality finishes (wood, acryli...', now(), now());
  INSERT INTO public.product_media (id, product_id, media_url, media_type, alt_text, display_order, is_primary)   VALUES ('082cf277-3009-4033-8c5d-71172c78781d', '6d9521dd-6a74-4152-a4ad-213c8387d760', 'SA002_main.jpg', 'image', 'Personalized Door Nameplate Image 1', 0, true);
  INSERT INTO public.product_media (id, product_id, media_url, media_type, alt_text, display_order, is_primary)   VALUES ('7814a13b-2728-44ef-afe3-cd4c3692cb67', '6d9521dd-6a74-4152-a4ad-213c8387d760', 'SA016_main.jpg', 'image', 'Personalized Door Nameplate Image 2', 1, false);
  INSERT INTO public.product_media (id, product_id, media_url, media_type, alt_text, display_order, is_primary)   VALUES ('e41a2f53-a493-4095-b9c6-e1c0c1f0162e', '6d9521dd-6a74-4152-a4ad-213c8387d760', 'SA024_main.jpg', 'image', 'Personalized Door Nameplate Image 3', 2, false);
  INSERT INTO public.product_media (id, product_id, media_url, media_type, alt_text, display_order, is_primary)   VALUES ('e7105a01-5ff6-4ae3-bf5e-8643f83b6f72', '6d9521dd-6a74-4152-a4ad-213c8387d760', 'SA031_main.jpg', 'image', 'Personalized Door Nameplate Image 4', 3, false);
  INSERT INTO public.product_media (id, product_id, media_url, media_type, alt_text, display_order, is_primary)   VALUES ('d1829b4c-4e6c-404a-a290-156e2b968b86', '6d9521dd-6a74-4152-a4ad-213c8387d760', 'SA036_main.jpg', 'image', 'Personalized Door Nameplate Image 5', 4, false);
  INSERT INTO public.product_media (id, product_id, media_url, media_type, alt_text, display_order, is_primary)   VALUES ('19dde750-7788-4859-aa10-cf6fe0239119', '6d9521dd-6a74-4152-a4ad-213c8387d760', 'SA049_main.jpg', 'image', 'Personalized Door Nameplate Image 6', 5, false);
  INSERT INTO public.custom_options (id, product_id, label, input_type, required, options, display_order, is_active)   VALUES ('ca8c130e-b64d-4265-9cbd-66a13cab872d', '6d9521dd-6a74-4152-a4ad-213c8387d760', 'Name(s) to Display', 'text', true, NULL, 0, true);
  INSERT INTO public.custom_options (id, product_id, label, input_type, required, options, display_order, is_active)   VALUES ('4ea37005-0848-4539-9658-6f7e4aa86211', '6d9521dd-6a74-4152-a4ad-213c8387d760', 'Material Theme', 'dropdown', true, '["Natural Wood Finish", "Glossy Black Acrylic", "Rose Gold Titanium Plate"]'::jsonb, 1, true);
  INSERT INTO public.custom_options (id, product_id, label, input_type, required, options, display_order, is_active)   VALUES ('910a5eac-5286-4d19-8a8d-a7bbed934aca', '6d9521dd-6a74-4152-a4ad-213c8387d760', 'Mounting Type', 'dropdown', true, '["Wall Mount Screws", "Double-sided Industrial Tape", "Hanging Chain"]'::jsonb, 2, true);

-- Product: Personalized Desk Name Stand
INSERT INTO public.products (id, title, slug, short_description, description, category_id, base_price, currency, status, is_featured, is_customizable, estimated_delivery_days, material, color_theme, seo_title, seo_description, created_at, updated_at) VALUES ('c4414e5c-3eb1-42bc-bdb3-bba4867e7b7a', 'Personalized Desk Name Stand', 'personalized-desk-name-stand', 'Customized wooden or acrylic name stand designed for office desks, study tables, or reception counters. Showcases your name and designation in a sleek...', 'Customized wooden or acrylic name stand designed for office desks, study tables, or reception counters. Showcases your name and designation in a sleek, professional layout.', '762b098d-4ebd-4fe5-bdc1-5d9eb9dbdfbf', 399, 'INR', 'custom_order', false, True, 7, 'Acrylic', 'Black Gloss', 'Personalized Desk Name Stand', 'Customized wooden or acrylic name stand designed for office desks, study tables, or reception counters. Showcases your name and designation in a sleek...', now(), now());
  INSERT INTO public.product_media (id, product_id, media_url, media_type, alt_text, display_order, is_primary)   VALUES ('5812af8b-d6bb-4eb4-a6ea-eb0fd345d3d4', 'c4414e5c-3eb1-42bc-bdb3-bba4867e7b7a', 'SA003_main.jpg', 'image', 'Personalized Desk Name Stand Image 1', 0, true);
  INSERT INTO public.product_media (id, product_id, media_url, media_type, alt_text, display_order, is_primary)   VALUES ('e7add1af-4ee3-437c-9a16-200d69ec0281', 'c4414e5c-3eb1-42bc-bdb3-bba4867e7b7a', 'SA011_main.jpg', 'image', 'Personalized Desk Name Stand Image 2', 1, false);
  INSERT INTO public.custom_options (id, product_id, label, input_type, required, options, display_order, is_active)   VALUES ('35d89ae4-1414-4a07-b640-6316e0928baa', 'c4414e5c-3eb1-42bc-bdb3-bba4867e7b7a', 'Name to Display', 'text', true, NULL, 0, true);
  INSERT INTO public.custom_options (id, product_id, label, input_type, required, options, display_order, is_active)   VALUES ('5a781d7b-7a00-4b40-847c-ffcc7c7ec8e7', 'c4414e5c-3eb1-42bc-bdb3-bba4867e7b7a', 'Designation / Subtext', 'text', false, NULL, 1, true);
  INSERT INTO public.custom_options (id, product_id, label, input_type, required, options, display_order, is_active)   VALUES ('5cb6606b-02e4-4251-9b31-0b1aff89ae0e', 'c4414e5c-3eb1-42bc-bdb3-bba4867e7b7a', 'Material Type', 'dropdown', true, '["Premium Oak Wood", "Dark Walnut Wood", "Black Acrylic"]'::jsonb, 2, true);

-- Product: Personalized Desk Name Stand with Pen Holder
INSERT INTO public.products (id, title, slug, short_description, description, category_id, base_price, currency, status, is_featured, is_customizable, estimated_delivery_days, material, color_theme, seo_title, seo_description, created_at, updated_at) VALUES ('b184364d-e01e-4df3-92d9-97041fa0e1ad', 'Personalized Desk Name Stand with Pen Holder', 'personalized-desk-name-stand-with-pen-holder', 'Functional and elegant desk organizer combining a customized name stand with integrated pen/pencil slots. Hand-crafted from premium wood materials, id...', 'Functional and elegant desk organizer combining a customized name stand with integrated pen/pencil slots. Hand-crafted from premium wood materials, ideal for professionals, lawyers, and advocates.', '762b098d-4ebd-4fe5-bdc1-5d9eb9dbdfbf', 599, 'INR', 'custom_order', false, True, 7, 'Metal', 'Natural Oak', 'Personalized Desk Name Stand with Pen Holder', 'Functional and elegant desk organizer combining a customized name stand with integrated pen/pencil slots. Hand-crafted from premium wood materials, id...', now(), now());
  INSERT INTO public.product_media (id, product_id, media_url, media_type, alt_text, display_order, is_primary)   VALUES ('5eaeefe8-3915-4e88-84dd-ca9b722591f1', 'b184364d-e01e-4df3-92d9-97041fa0e1ad', 'SA035_main.jpg', 'image', 'Personalized Desk Name Stand with Pen Holder Image 1', 0, true);
  INSERT INTO public.product_media (id, product_id, media_url, media_type, alt_text, display_order, is_primary)   VALUES ('89284cc2-2350-4ed5-8ded-110495468cb0', 'b184364d-e01e-4df3-92d9-97041fa0e1ad', 'SA038_main.jpg', 'image', 'Personalized Desk Name Stand with Pen Holder Image 2', 1, false);
  INSERT INTO public.product_media (id, product_id, media_url, media_type, alt_text, display_order, is_primary)   VALUES ('56ed6ef9-60c5-4fd3-9ba0-9c75b157ef39', 'b184364d-e01e-4df3-92d9-97041fa0e1ad', 'SA048_main.jpg', 'image', 'Personalized Desk Name Stand with Pen Holder Image 3', 2, false);
  INSERT INTO public.custom_options (id, product_id, label, input_type, required, options, display_order, is_active)   VALUES ('4e626b92-95fb-489a-ab69-055ebc4ac57d', 'b184364d-e01e-4df3-92d9-97041fa0e1ad', 'Name to Display', 'text', true, NULL, 0, true);
  INSERT INTO public.custom_options (id, product_id, label, input_type, required, options, display_order, is_active)   VALUES ('8f3b7e6e-2bdb-4cbe-8701-d1c523f1ce04', 'b184364d-e01e-4df3-92d9-97041fa0e1ad', 'Designation / Logo (e.g., Law Scales)', 'text', false, NULL, 1, true);
  INSERT INTO public.custom_options (id, product_id, label, input_type, required, options, display_order, is_active)   VALUES ('332c0bb1-fea3-41dc-a813-41b0de5e6b8e', 'b184364d-e01e-4df3-92d9-97041fa0e1ad', 'Pen Slots Quantity', 'dropdown', true, '["Single Slot", "Double Slot", "Multi-slot Organizer"]'::jsonb, 2, true);

-- Product: Custom Wooden Pen Stand & Organizer
INSERT INTO public.products (id, title, slug, short_description, description, category_id, base_price, currency, status, is_featured, is_customizable, estimated_delivery_days, material, color_theme, seo_title, seo_description, created_at, updated_at) VALUES ('05f4cbb4-1c33-4bca-9fde-f1c06a01f6a0', 'Custom Wooden Pen Stand & Organizer', 'custom-wooden-pen-stand-organizer', 'Premium desk pen stand engraved with your company logo, personal brand, or custom name. Made from high-quality polished wood, it makes an excellent co...', 'Premium desk pen stand engraved with your company logo, personal brand, or custom name. Made from high-quality polished wood, it makes an excellent corporate or office gift.', '762b098d-4ebd-4fe5-bdc1-5d9eb9dbdfbf', 299, 'INR', 'custom_order', false, True, 7, 'Wood', 'Natural Light', 'Custom Wooden Pen Stand & Organizer', 'Premium desk pen stand engraved with your company logo, personal brand, or custom name. Made from high-quality polished wood, it makes an excellent co...', now(), now());
  INSERT INTO public.product_media (id, product_id, media_url, media_type, alt_text, display_order, is_primary)   VALUES ('c5ec490d-0854-4194-9950-9dbe31c35e4f', '05f4cbb4-1c33-4bca-9fde-f1c06a01f6a0', 'SA047_main.jpg', 'image', 'Custom Wooden Pen Stand & Organizer Image 1', 0, true);
  INSERT INTO public.custom_options (id, product_id, label, input_type, required, options, display_order, is_active)   VALUES ('4ff3736d-07e8-416b-98bb-0c44b52e028a', '05f4cbb4-1c33-4bca-9fde-f1c06a01f6a0', 'Engraving Text / Logo Details', 'text', true, NULL, 0, true);
  INSERT INTO public.custom_options (id, product_id, label, input_type, required, options, display_order, is_active)   VALUES ('deaa6218-6850-42f9-9a6c-5c1f9bd7e2e9', '05f4cbb4-1c33-4bca-9fde-f1c06a01f6a0', 'Wood Color', 'dropdown', true, '["Natural Light Wood", "Polished Mahogany"]'::jsonb, 1, true);

-- Product: Custom Engraved Name Pen
INSERT INTO public.products (id, title, slug, short_description, description, category_id, base_price, currency, status, is_featured, is_customizable, estimated_delivery_days, material, color_theme, seo_title, seo_description, created_at, updated_at) VALUES ('ba467c21-c7cb-47d2-8822-529b2fd81f58', 'Custom Engraved Name Pen', 'custom-engraved-name-pen', 'Sleek metal body pen custom-engraved with your name. Features smooth ink flow and a premium feel. Packaged elegantly, making it a thoughtful gift for ...', 'Sleek metal body pen custom-engraved with your name. Features smooth ink flow and a premium feel. Packaged elegantly, making it a thoughtful gift for writers, teachers, and professionals.', '3d32729c-0589-4aef-9e3e-99a3e21f1185', 199, 'INR', 'custom_order', false, True, 7, 'Metal', 'Glossy Silver', 'Custom Engraved Name Pen', 'Sleek metal body pen custom-engraved with your name. Features smooth ink flow and a premium feel. Packaged elegantly, making it a thoughtful gift for ...', now(), now());
  INSERT INTO public.product_media (id, product_id, media_url, media_type, alt_text, display_order, is_primary)   VALUES ('a3361e38-36f7-48eb-92ff-8f631dc3784c', 'ba467c21-c7cb-47d2-8822-529b2fd81f58', 'SA010_main.jpg', 'image', 'Custom Engraved Name Pen Image 1', 0, true);
  INSERT INTO public.product_media (id, product_id, media_url, media_type, alt_text, display_order, is_primary)   VALUES ('e475c5e9-e0a3-40ba-92d5-349fdfcf0b19', 'ba467c21-c7cb-47d2-8822-529b2fd81f58', 'SA020_main.jpg', 'image', 'Custom Engraved Name Pen Image 2', 1, false);
  INSERT INTO public.product_media (id, product_id, media_url, media_type, alt_text, display_order, is_primary)   VALUES ('60fcb2de-d337-42f8-bfc1-f27c2a458c02', 'ba467c21-c7cb-47d2-8822-529b2fd81f58', 'SA030_main.jpg', 'image', 'Custom Engraved Name Pen Image 3', 2, false);
  INSERT INTO public.product_media (id, product_id, media_url, media_type, alt_text, display_order, is_primary)   VALUES ('b173ab7e-646f-40cd-90eb-23f657ab531f', 'ba467c21-c7cb-47d2-8822-529b2fd81f58', 'SA063_main.jpg', 'image', 'Custom Engraved Name Pen Image 4', 3, false);
  INSERT INTO public.custom_options (id, product_id, label, input_type, required, options, display_order, is_active)   VALUES ('c96bebbb-e9f1-423f-b0ab-4c68f8adf6f6', 'ba467c21-c7cb-47d2-8822-529b2fd81f58', 'Name to Engrave', 'text', true, NULL, 0, true);
  INSERT INTO public.custom_options (id, product_id, label, input_type, required, options, display_order, is_active)   VALUES ('202a1637-1b9c-4a3f-8389-f716dd2355b0', 'ba467c21-c7cb-47d2-8822-529b2fd81f58', 'Pen Body Color', 'dropdown', true, '["Matte Black with Gold Trim", "Glossy Silver", "Metallic Blue"]'::jsonb, 1, true);

-- Product: Custom Engraved Stainless Steel Bottle
INSERT INTO public.products (id, title, slug, short_description, description, category_id, base_price, currency, status, is_featured, is_customizable, estimated_delivery_days, material, color_theme, seo_title, seo_description, created_at, updated_at) VALUES ('412ae2a2-1454-4f22-8b13-fa888b4a5903', 'Custom Engraved Stainless Steel Bottle', 'custom-engraved-stainless-steel-bottle', 'Durable, eco-friendly stainless steel water bottle personalized with high-precision laser engraving. Leakproof and designed for daily use at school, o...', 'Durable, eco-friendly stainless steel water bottle personalized with high-precision laser engraving. Leakproof and designed for daily use at school, office, or gym.', 'c2019c04-21df-4ac1-9493-4e5d8f6eb6d3', 499, 'INR', 'custom_order', false, True, 7, 'Stainless Steel', 'Blue', 'Custom Engraved Stainless Steel Bottle', 'Durable, eco-friendly stainless steel water bottle personalized with high-precision laser engraving. Leakproof and designed for daily use at school, o...', now(), now());
  INSERT INTO public.product_media (id, product_id, media_url, media_type, alt_text, display_order, is_primary)   VALUES ('523aecd0-42c9-4931-8af7-03681570cec4', '412ae2a2-1454-4f22-8b13-fa888b4a5903', 'SA019_main.jpg', 'image', 'Custom Engraved Stainless Steel Bottle Image 1', 0, true);
  INSERT INTO public.product_media (id, product_id, media_url, media_type, alt_text, display_order, is_primary)   VALUES ('c77c5ba3-edbe-441f-b4e5-6b19ed84b3a5', '412ae2a2-1454-4f22-8b13-fa888b4a5903', 'SA041_main.jpg', 'image', 'Custom Engraved Stainless Steel Bottle Image 2', 1, false);
  INSERT INTO public.custom_options (id, product_id, label, input_type, required, options, display_order, is_active)   VALUES ('1d98dc15-0f6e-4fdd-8cfc-3e96a9d3dc53', '412ae2a2-1454-4f22-8b13-fa888b4a5903', 'Name / Text to Engrave', 'text', true, NULL, 0, true);
  INSERT INTO public.custom_options (id, product_id, label, input_type, required, options, display_order, is_active)   VALUES ('7393d313-a0c9-4aeb-a5ad-b9770dae5e1c', '412ae2a2-1454-4f22-8b13-fa888b4a5903', 'Bottle Color', 'dropdown', true, '["Matte Black", "Metallic Silver", "Vibrant Red", "Deep Blue"]'::jsonb, 1, true);

-- Product: Custom Leatherette Diary
INSERT INTO public.products (id, title, slug, short_description, description, category_id, base_price, currency, status, is_featured, is_customizable, estimated_delivery_days, material, color_theme, seo_title, seo_description, created_at, updated_at) VALUES ('89e8a9c2-8905-47ba-9b2c-4093ac0c77c0', 'Custom Leatherette Diary', 'custom-leatherette-diary', 'Elegant leatherette cover diary with personalized name engraving or logo UV print. Includes ruled sheets of high-quality paper, ideal for journaling, ...', 'Elegant leatherette cover diary with personalized name engraving or logo UV print. Includes ruled sheets of high-quality paper, ideal for journaling, note-taking, or corporate planning.', '93d59815-87b9-4a3f-b0e4-a3b59b63d9c9', 349, 'INR', 'custom_order', false, True, 7, 'Leatherette', 'Black', 'Custom Leatherette Diary', 'Elegant leatherette cover diary with personalized name engraving or logo UV print. Includes ruled sheets of high-quality paper, ideal for journaling, ...', now(), now());
  INSERT INTO public.product_media (id, product_id, media_url, media_type, alt_text, display_order, is_primary)   VALUES ('b2731a3c-4656-4be7-b9bc-e30ec3d05a4d', '89e8a9c2-8905-47ba-9b2c-4093ac0c77c0', 'SA052_main.jpg', 'image', 'Custom Leatherette Diary Image 1', 0, true);
  INSERT INTO public.custom_options (id, product_id, label, input_type, required, options, display_order, is_active)   VALUES ('5f9f5be6-53d8-445c-9eb2-5c7894e3944d', '89e8a9c2-8905-47ba-9b2c-4093ac0c77c0', 'Name to Engrave / Emboss', 'text', true, NULL, 0, true);
  INSERT INTO public.custom_options (id, product_id, label, input_type, required, options, display_order, is_active)   VALUES ('8c15b480-dbc2-4f9e-8b5a-7dd514e2de9f', '89e8a9c2-8905-47ba-9b2c-4093ac0c77c0', 'Diary Cover Color', 'dropdown', true, '["Classic Brown", "Midnight Black", "Tan Leather", "Navy Blue"]'::jsonb, 1, true);

-- Product: Executive Diary & Engraved Pen Gift Set
INSERT INTO public.products (id, title, slug, short_description, description, category_id, base_price, currency, status, is_featured, is_customizable, estimated_delivery_days, material, color_theme, seo_title, seo_description, created_at, updated_at) VALUES ('7bea4b0d-ad92-484d-bc68-b1dd75730408', 'Executive Diary & Engraved Pen Gift Set', 'executive-diary-engraved-pen-gift-set', 'A premium gift combo containing a personalized leatherette diary and a matching custom-engraved name pen. Perfectly packaged in a gift box, making it ...', 'A premium gift combo containing a personalized leatherette diary and a matching custom-engraved name pen. Perfectly packaged in a gift box, making it a highly professional corporate gift set.', '93d59815-87b9-4a3f-b0e4-a3b59b63d9c9', 549, 'INR', 'custom_order', false, True, 7, 'Leatherette', 'Matching Black', 'Executive Diary & Engraved Pen Gift Set', 'A premium gift combo containing a personalized leatherette diary and a matching custom-engraved name pen. Perfectly packaged in a gift box, making it ...', now(), now());
  INSERT INTO public.product_media (id, product_id, media_url, media_type, alt_text, display_order, is_primary)   VALUES ('1e4418c8-970c-4f55-93e0-1bf207fb65eb', '7bea4b0d-ad92-484d-bc68-b1dd75730408', 'SA056_main.jpg', 'image', 'Executive Diary & Engraved Pen Gift Set Image 1', 0, true);
  INSERT INTO public.product_media (id, product_id, media_url, media_type, alt_text, display_order, is_primary)   VALUES ('7d1534e7-b2bf-49fa-99bf-20398ea2ad71', '7bea4b0d-ad92-484d-bc68-b1dd75730408', 'SA059_main.jpg', 'image', 'Executive Diary & Engraved Pen Gift Set Image 2', 1, false);
  INSERT INTO public.custom_options (id, product_id, label, input_type, required, options, display_order, is_active)   VALUES ('a4ace107-1ff7-4592-823e-d507ab125312', '7bea4b0d-ad92-484d-bc68-b1dd75730408', 'Name for Diary & Pen', 'text', true, NULL, 0, true);
  INSERT INTO public.custom_options (id, product_id, label, input_type, required, options, display_order, is_active)   VALUES ('13dedd82-79fa-4358-bb19-49866089c1da', '7bea4b0d-ad92-484d-bc68-b1dd75730408', 'Gift Set Theme Color', 'dropdown', true, '["Matching Brown Set", "Matching Black Set", "Tan Leather Set"]'::jsonb, 1, true);

-- Product: Custom Acrylic / ACP UV Printed Photo Plaque
INSERT INTO public.products (id, title, slug, short_description, description, category_id, base_price, currency, status, is_featured, is_customizable, estimated_delivery_days, material, color_theme, seo_title, seo_description, created_at, updated_at) VALUES ('30b72791-6663-4a19-9ff0-45cefab102ea', 'Custom Acrylic / ACP UV Printed Photo Plaque', 'custom-acrylic-acp-uv-printed-photo-plaque', 'High-definition UV printing directly on acrylic or aluminum composite panels (ACP). Captures vibrant colors and fine details, creating a modern, borde...', 'High-definition UV printing directly on acrylic or aluminum composite panels (ACP). Captures vibrant colors and fine details, creating a modern, borderless frame effect for photos, memorials, or brand statements.', '1dfa9b3b-c736-4c9b-a09a-cf0323510ec2', 699, 'INR', 'custom_order', false, True, 7, 'ACP Panel', 'Multicolor UV Print', 'Custom Acrylic / ACP UV Printed Photo Plaque', 'High-definition UV printing directly on acrylic or aluminum composite panels (ACP). Captures vibrant colors and fine details, creating a modern, borde...', now(), now());
  INSERT INTO public.product_media (id, product_id, media_url, media_type, alt_text, display_order, is_primary)   VALUES ('6fb2088a-f579-4472-b917-051ed88d5e21', '30b72791-6663-4a19-9ff0-45cefab102ea', 'SA005_main.jpg', 'image', 'Custom Acrylic / ACP UV Printed Photo Plaque Image 1', 0, true);
  INSERT INTO public.product_media (id, product_id, media_url, media_type, alt_text, display_order, is_primary)   VALUES ('8e0b4853-3a06-4ba3-bfdb-33cbb3995cac', '30b72791-6663-4a19-9ff0-45cefab102ea', 'SA040_main.jpg', 'image', 'Custom Acrylic / ACP UV Printed Photo Plaque Image 2', 1, false);
  INSERT INTO public.custom_options (id, product_id, label, input_type, required, options, display_order, is_active)   VALUES ('e08bb5b4-f495-4afd-8461-2958a939438f', '30b72791-6663-4a19-9ff0-45cefab102ea', 'Photo Upload / Text Details', 'text', true, NULL, 0, true);
  INSERT INTO public.custom_options (id, product_id, label, input_type, required, options, display_order, is_active)   VALUES ('ff812725-2ca8-451d-8e57-5d377e448530', '30b72791-6663-4a19-9ff0-45cefab102ea', 'Material Type', 'dropdown', true, '["Glossy Acrylic (3mm)", "ACP Brushed Metal Finish"]'::jsonb, 1, true);
  INSERT INTO public.custom_options (id, product_id, label, input_type, required, options, display_order, is_active)   VALUES ('4fafc322-f490-4eac-a36b-f4c68339e1c4', '30b72791-6663-4a19-9ff0-45cefab102ea', 'Size Option', 'dropdown', true, '["A5 Small", "A4 Medium", "A3 Large"]'::jsonb, 2, true);

-- Product: Custom Acrylic Trophy & Memento
INSERT INTO public.products (id, title, slug, short_description, description, category_id, base_price, currency, status, is_featured, is_customizable, estimated_delivery_days, material, color_theme, seo_title, seo_description, created_at, updated_at) VALUES ('18db2d44-f596-4423-86ca-8447833802e8', 'Custom Acrylic Trophy & Memento', 'custom-acrylic-trophy-memento', 'Tailor-made trophies and mementos designed for corporate achievements, festivals, or family appreciation (e.g. ''Best Sister''). Features high-precision...', 'Tailor-made trophies and mementos designed for corporate achievements, festivals, or family appreciation (e.g. ''Best Sister''). Features high-precision acrylic cutting and custom printing.', 'a845de12-2673-4fe9-ae01-96e498d29091', 349, 'INR', 'custom_order', false, True, 7, 'Acrylic', 'Custom Printing', 'Custom Acrylic Trophy & Memento', 'Tailor-made trophies and mementos designed for corporate achievements, festivals, or family appreciation (e.g. ''Best Sister''). Features high-precision...', now(), now());
  INSERT INTO public.product_media (id, product_id, media_url, media_type, alt_text, display_order, is_primary)   VALUES ('317ce917-5a52-4dde-af3f-c2da33111dbf', '18db2d44-f596-4423-86ca-8447833802e8', 'SA007_main.jpg', 'image', 'Custom Acrylic Trophy & Memento Image 1', 0, true);
  INSERT INTO public.product_media (id, product_id, media_url, media_type, alt_text, display_order, is_primary)   VALUES ('705fc8e0-7107-4b87-9b7b-da18d4636e41', '18db2d44-f596-4423-86ca-8447833802e8', 'SA029_main.jpg', 'image', 'Custom Acrylic Trophy & Memento Image 2', 1, false);
  INSERT INTO public.product_media (id, product_id, media_url, media_type, alt_text, display_order, is_primary)   VALUES ('6093bc70-30dd-4186-9d84-864862c25bba', '18db2d44-f596-4423-86ca-8447833802e8', 'SA051_main.jpg', 'image', 'Custom Acrylic Trophy & Memento Image 3', 2, false);
  INSERT INTO public.custom_options (id, product_id, label, input_type, required, options, display_order, is_active)   VALUES ('efa756a0-db7d-40b5-9975-af34369040b0', '18db2d44-f596-4423-86ca-8447833802e8', 'Title Text', 'text', true, NULL, 0, true);
  INSERT INTO public.custom_options (id, product_id, label, input_type, required, options, display_order, is_active)   VALUES ('21a925ff-d4f6-4aa4-a516-6698867d0b66', '18db2d44-f596-4423-86ca-8447833802e8', 'Awardee / Subtext', 'text', false, NULL, 1, true);
  INSERT INTO public.custom_options (id, product_id, label, input_type, required, options, display_order, is_active)   VALUES ('6642042a-26bb-4700-bc5e-cbc8f38572ff', '18db2d44-f596-4423-86ca-8447833802e8', 'Trophy Shape', 'dropdown', true, '["Star Shield", "Classic Rectangular", "Custom Cutout Shape"]'::jsonb, 2, true);

-- Product: Personalized Metal Kada / Bracelet
INSERT INTO public.products (id, title, slug, short_description, description, category_id, base_price, currency, status, is_featured, is_customizable, estimated_delivery_days, material, color_theme, seo_title, seo_description, created_at, updated_at) VALUES ('f54277cf-fbce-413a-b231-224c1deaf6f7', 'Personalized Metal Kada / Bracelet', 'personalized-metal-kada-bracelet', 'Stylish, adjustable stainless steel Kada (wrist bracelet) customized with your name or special text engraved. Comfortable for daily wear and resistant...', 'Stylish, adjustable stainless steel Kada (wrist bracelet) customized with your name or special text engraved. Comfortable for daily wear and resistant to rust or tarnishing.', '43f86136-c0d7-40b8-a49e-3aad3fe1ad28', 299, 'INR', 'custom_order', false, True, 7, 'Stainless Steel', 'Gold', 'Personalized Metal Kada / Bracelet', 'Stylish, adjustable stainless steel Kada (wrist bracelet) customized with your name or special text engraved. Comfortable for daily wear and resistant...', now(), now());
  INSERT INTO public.product_media (id, product_id, media_url, media_type, alt_text, display_order, is_primary)   VALUES ('2d988eb9-cb80-4785-a96d-25d4ffd1408f', 'f54277cf-fbce-413a-b231-224c1deaf6f7', 'SA057_main.jpg', 'image', 'Personalized Metal Kada / Bracelet Image 1', 0, true);
  INSERT INTO public.custom_options (id, product_id, label, input_type, required, options, display_order, is_active)   VALUES ('481f0301-5a33-4ab3-8a5d-e7d7616d75ed', 'f54277cf-fbce-413a-b231-224c1deaf6f7', 'Name to Engrave', 'text', true, NULL, 0, true);
  INSERT INTO public.custom_options (id, product_id, label, input_type, required, options, display_order, is_active)   VALUES ('96c1e07d-48aa-4b92-ad81-e455a1c0ff11', 'f54277cf-fbce-413a-b231-224c1deaf6f7', 'Finish Option', 'dropdown', true, '["Polished Silver", "Rose Gold", "Gold Plated"]'::jsonb, 1, true);

-- Product: Custom Pearl Pendant Necklace
INSERT INTO public.products (id, title, slug, short_description, description, category_id, base_price, currency, status, is_featured, is_customizable, estimated_delivery_days, material, color_theme, seo_title, seo_description, created_at, updated_at) VALUES ('f3f09533-dc6d-46d6-ad7b-feaeb69d3cc8', 'Custom Pearl Pendant Necklace', 'custom-pearl-pendant-necklace', 'Elegant necklace featuring a pearl accent and a customized locket pendant. A delicate and beautiful jewelry piece perfect for special occasions, anniv...', 'Elegant necklace featuring a pearl accent and a customized locket pendant. A delicate and beautiful jewelry piece perfect for special occasions, anniversaries, or Valentine''s gifting.', '43f86136-c0d7-40b8-a49e-3aad3fe1ad28', 399, 'INR', 'custom_order', false, True, 7, 'Metal', 'Gold', 'Custom Pearl Pendant Necklace', 'Elegant necklace featuring a pearl accent and a customized locket pendant. A delicate and beautiful jewelry piece perfect for special occasions, anniv...', now(), now());
  INSERT INTO public.product_media (id, product_id, media_url, media_type, alt_text, display_order, is_primary)   VALUES ('8108f5c6-cd17-475e-89d5-00130b2ff103', 'f3f09533-dc6d-46d6-ad7b-feaeb69d3cc8', 'SA055_main.jpg', 'image', 'Custom Pearl Pendant Necklace Image 1', 0, true);
  INSERT INTO public.custom_options (id, product_id, label, input_type, required, options, display_order, is_active)   VALUES ('2ceb27be-8b30-4472-8655-323978d8a0c4', 'f3f09533-dc6d-46d6-ad7b-feaeb69d3cc8', 'Locket Text / Initial', 'text', true, NULL, 0, true);
  INSERT INTO public.custom_options (id, product_id, label, input_type, required, options, display_order, is_active)   VALUES ('830bcc88-a170-4cdb-8f4f-736da97ab8c5', 'f3f09533-dc6d-46d6-ad7b-feaeb69d3cc8', 'Locket Finish', 'dropdown', true, '["Rose Gold", "Gold Plated", "Silver Finish"]'::jsonb, 1, true);

-- Product: Custom Engraved Pet Name Tag
INSERT INTO public.products (id, title, slug, short_description, description, category_id, base_price, currency, status, is_featured, is_customizable, estimated_delivery_days, material, color_theme, seo_title, seo_description, created_at, updated_at) VALUES ('d0b1ae2e-f2a7-4dcc-b3e3-77a03e4359f6', 'Custom Engraved Pet Name Tag', 'custom-engraved-pet-name-tag', 'Mini name tags for dogs and cats. Custom engraved with the pet''s name on the front and owner''s contact details on the back. Lightweight, rustproof, an...', 'Mini name tags for dogs and cats. Custom engraved with the pet''s name on the front and owner''s contact details on the back. Lightweight, rustproof, and designed to attach easily to collars.', 'd874298a-8c26-444b-9f08-b5ce90d7444c', 129, 'INR', 'custom_order', false, True, 7, 'Metal', 'Blue', 'Custom Engraved Pet Name Tag', 'Mini name tags for dogs and cats. Custom engraved with the pet''s name on the front and owner''s contact details on the back. Lightweight, rustproof, an...', now(), now());
  INSERT INTO public.product_media (id, product_id, media_url, media_type, alt_text, display_order, is_primary)   VALUES ('0938e059-ca52-42f3-b5f5-d33ac0f89c2f', 'd0b1ae2e-f2a7-4dcc-b3e3-77a03e4359f6', 'SA006_main.jpg', 'image', 'Custom Engraved Pet Name Tag Image 1', 0, true);
  INSERT INTO public.custom_options (id, product_id, label, input_type, required, options, display_order, is_active)   VALUES ('0fc959de-8fb9-4b54-8fde-ecc5e96bf608', 'd0b1ae2e-f2a7-4dcc-b3e3-77a03e4359f6', 'Pet''s Name', 'text', true, NULL, 0, true);
  INSERT INTO public.custom_options (id, product_id, label, input_type, required, options, display_order, is_active)   VALUES ('6e69a6fe-05d8-4192-9f82-a20eba3e3823', 'd0b1ae2e-f2a7-4dcc-b3e3-77a03e4359f6', 'Owner''s Phone Number', 'text', true, NULL, 1, true);
  INSERT INTO public.custom_options (id, product_id, label, input_type, required, options, display_order, is_active)   VALUES ('378f6857-973f-424a-be8b-fb1c71f573a8', 'd0b1ae2e-f2a7-4dcc-b3e3-77a03e4359f6', 'Tag Shape', 'dropdown', true, '["Bone Shape", "Heart Shape", "Classic Circle"]'::jsonb, 2, true);

-- Product: Custom 3D Metal / Acrylic Letters
INSERT INTO public.products (id, title, slug, short_description, description, category_id, base_price, currency, status, is_featured, is_customizable, estimated_delivery_days, material, color_theme, seo_title, seo_description, created_at, updated_at) VALUES ('f3d847d6-eec3-4611-b126-482f76715708', 'Custom 3D Metal / Acrylic Letters', 'custom-3d-metal-acrylic-letters', 'Premium 3D individual cut-out letters made of stainless steel (SS Rose Gold, Titanium) or acrylic. Perfect for mounting on home bungalow walls, buildi...', 'Premium 3D individual cut-out letters made of stainless steel (SS Rose Gold, Titanium) or acrylic. Perfect for mounting on home bungalow walls, building facades, or office reception backdrops.', 'a54663f6-2941-43a9-a526-ddb81190df21', 1999, 'INR', 'custom_order', false, True, 7, 'Acrylic', 'Black', 'Custom 3D Metal / Acrylic Letters', 'Premium 3D individual cut-out letters made of stainless steel (SS Rose Gold, Titanium) or acrylic. Perfect for mounting on home bungalow walls, buildi...', now(), now());
  INSERT INTO public.product_media (id, product_id, media_url, media_type, alt_text, display_order, is_primary)   VALUES ('78bb63cf-c5fd-47a0-9692-436f5781f865', 'f3d847d6-eec3-4611-b126-482f76715708', 'SA022_main.jpg', 'image', 'Custom 3D Metal / Acrylic Letters Image 1', 0, true);
  INSERT INTO public.product_media (id, product_id, media_url, media_type, alt_text, display_order, is_primary)   VALUES ('b8bf25f3-84ba-46ae-a78a-783389821ecc', 'f3d847d6-eec3-4611-b126-482f76715708', 'SA026_main.jpg', 'image', 'Custom 3D Metal / Acrylic Letters Image 2', 1, false);
  INSERT INTO public.custom_options (id, product_id, label, input_type, required, options, display_order, is_active)   VALUES ('2319621e-aba8-43f1-9db7-e93864d08cec', 'f3d847d6-eec3-4611-b126-482f76715708', 'Text to Display', 'text', true, NULL, 0, true);
  INSERT INTO public.custom_options (id, product_id, label, input_type, required, options, display_order, is_active)   VALUES ('e4999fa2-cc09-4f01-a18d-83ae68ef7c11', 'f3d847d6-eec3-4611-b126-482f76715708', 'Material / Color Finish', 'dropdown', true, '["SS Rose Gold Titanium", "SS Mirror Gold", "Glossy Black Acrylic", "White Acrylic"]'::jsonb, 1, true);
  INSERT INTO public.custom_options (id, product_id, label, input_type, required, options, display_order, is_active)   VALUES ('e3e7c815-3523-4dfb-9728-9e08974a15d7', 'f3d847d6-eec3-4611-b126-482f76715708', 'Letter Height (inches)', 'dropdown', true, '["4 inches", "6 inches", "8 inches", "12 inches", "Custom Size"]'::jsonb, 2, true);

-- Product: Custom Business Signage & Branding Plate
INSERT INTO public.products (id, title, slug, short_description, description, category_id, base_price, currency, status, is_featured, is_customizable, estimated_delivery_days, material, color_theme, seo_title, seo_description, created_at, updated_at) VALUES ('6c2aee3c-dfd4-4561-9e6b-07431d641aea', 'Custom Business Signage & Branding Plate', 'custom-business-signage-branding-plate', 'Customized brand signs, signage frames, machine rating plates, and promotional branding plates. Tailor-made for storefronts, industrial machinery labe...', 'Customized brand signs, signage frames, machine rating plates, and promotional branding plates. Tailor-made for storefronts, industrial machinery labeling, or brand setups.', 'a54663f6-2941-43a9-a526-ddb81190df21', 999, 'INR', 'custom_order', false, True, 7, 'ACP Panel', 'Custom Design', 'Custom Business Signage & Branding Plate', 'Customized brand signs, signage frames, machine rating plates, and promotional branding plates. Tailor-made for storefronts, industrial machinery labe...', now(), now());
  INSERT INTO public.product_media (id, product_id, media_url, media_type, alt_text, display_order, is_primary)   VALUES ('22ea04c5-6b9e-42f9-abd0-ae5210e7e926', '6c2aee3c-dfd4-4561-9e6b-07431d641aea', 'SA014_main.jpg', 'image', 'Custom Business Signage & Branding Plate Image 1', 0, true);
  INSERT INTO public.product_media (id, product_id, media_url, media_type, alt_text, display_order, is_primary)   VALUES ('51a35cde-0067-43af-bc33-8d13ef7f9d75', '6c2aee3c-dfd4-4561-9e6b-07431d641aea', 'SA037_main.jpg', 'image', 'Custom Business Signage & Branding Plate Image 2', 1, false);
  INSERT INTO public.product_media (id, product_id, media_url, media_type, alt_text, display_order, is_primary)   VALUES ('1e0e2f45-fdb4-463e-8fbf-f3a3c1be7c94', '6c2aee3c-dfd4-4561-9e6b-07431d641aea', 'SA039_main.jpg', 'image', 'Custom Business Signage & Branding Plate Image 3', 2, false);
  INSERT INTO public.product_media (id, product_id, media_url, media_type, alt_text, display_order, is_primary)   VALUES ('dd52e69d-0d52-48ba-afdc-84e9a16ce076', '6c2aee3c-dfd4-4561-9e6b-07431d641aea', 'SA044_main.jpg', 'image', 'Custom Business Signage & Branding Plate Image 4', 3, false);
  INSERT INTO public.product_media (id, product_id, media_url, media_type, alt_text, display_order, is_primary)   VALUES ('29732975-a112-454e-bdd2-734418c50ff3', '6c2aee3c-dfd4-4561-9e6b-07431d641aea', 'SA046_main.jpg', 'image', 'Custom Business Signage & Branding Plate Image 5', 4, false);
  INSERT INTO public.custom_options (id, product_id, label, input_type, required, options, display_order, is_active)   VALUES ('8f83d663-a9c3-4285-86b9-65845c72169c', '6c2aee3c-dfd4-4561-9e6b-07431d641aea', 'Signage Details / Requirements', 'text', true, NULL, 0, true);
  INSERT INTO public.custom_options (id, product_id, label, input_type, required, options, display_order, is_active)   VALUES ('7efaccc1-80b9-4f3f-84c9-09e005cc962e', '6c2aee3c-dfd4-4561-9e6b-07431d641aea', 'Material Selection', 'dropdown', true, '["Acrylic", "ACP Sheet", "Metal Engraved Plate"]'::jsonb, 1, true);

-- Product: Custom Religious / Decorative Art Plaque
INSERT INTO public.products (id, title, slug, short_description, description, category_id, base_price, currency, status, is_featured, is_customizable, estimated_delivery_days, material, color_theme, seo_title, seo_description, created_at, updated_at) VALUES ('1eda5917-c95b-44ec-af07-c0ca7adc5ca3', 'Custom Religious / Decorative Art Plaque', 'custom-religious-decorative-art-plaque', 'Artistic wall or desk plaques featuring Hindu deities (Ganesha, Swami Samarth, etc.) or decorative spiritual calligraphic motifs. Crafted with acrylic...', 'Artistic wall or desk plaques featuring Hindu deities (Ganesha, Swami Samarth, etc.) or decorative spiritual calligraphic motifs. Crafted with acrylic/wood overlays for a 3D layered look.', 'd86e9fbe-11a8-473d-8d84-508660843929', 499, 'INR', 'custom_order', false, True, 7, 'Acrylic', 'Golden', 'Custom Religious / Decorative Art Plaque', 'Artistic wall or desk plaques featuring Hindu deities (Ganesha, Swami Samarth, etc.) or decorative spiritual calligraphic motifs. Crafted with acrylic...', now(), now());
  INSERT INTO public.product_media (id, product_id, media_url, media_type, alt_text, display_order, is_primary)   VALUES ('c1a91caf-4118-40f0-93ac-19dc7bd62fbe', '1eda5917-c95b-44ec-af07-c0ca7adc5ca3', 'SA004_main.jpg', 'image', 'Custom Religious / Decorative Art Plaque Image 1', 0, true);
  INSERT INTO public.product_media (id, product_id, media_url, media_type, alt_text, display_order, is_primary)   VALUES ('6ff57228-b515-4a14-bfba-85ea6807b708', '1eda5917-c95b-44ec-af07-c0ca7adc5ca3', 'SA050_main.jpg', 'image', 'Custom Religious / Decorative Art Plaque Image 2', 1, false);
  INSERT INTO public.custom_options (id, product_id, label, input_type, required, options, display_order, is_active)   VALUES ('d4e47d7e-9c65-4cb7-a75a-d4e12ec8598b', '1eda5917-c95b-44ec-af07-c0ca7adc5ca3', 'Deity / Art Theme', 'dropdown', true, '["Ganesha Art", "Shree Swami Samarth", "Mahakal Calligraphy Art", "Custom Spiritual Symbol"]'::jsonb, 0, true);
  INSERT INTO public.custom_options (id, product_id, label, input_type, required, options, display_order, is_active)   VALUES ('e84f7fd0-3679-4deb-9dbc-026efba09b65', '1eda5917-c95b-44ec-af07-c0ca7adc5ca3', 'Mounting Type', 'dropdown', true, '["Wall Mount", "Desk Stand (with base)"]'::jsonb, 1, true);

-- Product: Non-Catalog Brand Showcase
INSERT INTO public.products (id, title, slug, short_description, description, category_id, base_price, currency, status, is_featured, is_customizable, estimated_delivery_days, material, color_theme, seo_title, seo_description, created_at, updated_at) VALUES ('882ce05b-e671-4a77-9a2b-23ffc7d91138', 'Non-Catalog Brand Showcase', 'non-catalog-brand-showcase', 'Portfolio posts showing Kalaasutra workshop capabilities, laser/UV machinery in action (e.g. UV marking machine setup), or general contact details. No...', 'Portfolio posts showing Kalaasutra workshop capabilities, laser/UV machinery in action (e.g. UV marking machine setup), or general contact details. Not a retail product.', '9df89dd9-ffcd-42bb-9ce9-75dba3cc5bfa', 0, 'INR', 'available', false, False, 7, NULL, 'Red', 'Non-Catalog Brand Showcase', 'Portfolio posts showing Kalaasutra workshop capabilities, laser/UV machinery in action (e.g. UV marking machine setup), or general contact details. No...', now(), now());
  INSERT INTO public.product_media (id, product_id, media_url, media_type, alt_text, display_order, is_primary)   VALUES ('3b994474-22b1-4ea0-b4be-e1df8449680b', '882ce05b-e671-4a77-9a2b-23ffc7d91138', 'SA008_main.jpg', 'image', 'Non-Catalog Brand Showcase Image 1', 0, true);
  INSERT INTO public.product_media (id, product_id, media_url, media_type, alt_text, display_order, is_primary)   VALUES ('6bf055b9-2b86-40f8-98f3-81675fee95f7', '882ce05b-e671-4a77-9a2b-23ffc7d91138', 'SA013_main.jpg', 'image', 'Non-Catalog Brand Showcase Image 2', 1, false);
  INSERT INTO public.product_media (id, product_id, media_url, media_type, alt_text, display_order, is_primary)   VALUES ('77efd62c-703f-4b59-a604-4bde80ab2d8d', '882ce05b-e671-4a77-9a2b-23ffc7d91138', 'SA017_main.jpg', 'image', 'Non-Catalog Brand Showcase Image 3', 2, false);
  INSERT INTO public.product_media (id, product_id, media_url, media_type, alt_text, display_order, is_primary)   VALUES ('7d022631-f580-47fe-b426-1f01a04c8d89', '882ce05b-e671-4a77-9a2b-23ffc7d91138', 'SA025_main.jpg', 'image', 'Non-Catalog Brand Showcase Image 4', 3, false);
  INSERT INTO public.product_media (id, product_id, media_url, media_type, alt_text, display_order, is_primary)   VALUES ('781f7df2-6260-4c41-aa50-475ec3dad940', '882ce05b-e671-4a77-9a2b-23ffc7d91138', 'SA027_main.jpg', 'image', 'Non-Catalog Brand Showcase Image 5', 4, false);
  INSERT INTO public.product_media (id, product_id, media_url, media_type, alt_text, display_order, is_primary)   VALUES ('173afd21-8b4d-4599-9f7f-e30ea7d4d3f8', '882ce05b-e671-4a77-9a2b-23ffc7d91138', 'SA028_main.jpg', 'image', 'Non-Catalog Brand Showcase Image 6', 5, false);
  INSERT INTO public.product_media (id, product_id, media_url, media_type, alt_text, display_order, is_primary)   VALUES ('6a217952-c4ea-46cc-96c6-f473632aa38f', '882ce05b-e671-4a77-9a2b-23ffc7d91138', 'SA032_main.jpg', 'image', 'Non-Catalog Brand Showcase Image 7', 6, false);
  INSERT INTO public.product_media (id, product_id, media_url, media_type, alt_text, display_order, is_primary)   VALUES ('19f9f40c-3c44-49cd-b842-92f5c91acae6', '882ce05b-e671-4a77-9a2b-23ffc7d91138', 'SA034_main.jpg', 'image', 'Non-Catalog Brand Showcase Image 8', 7, false);
  INSERT INTO public.product_media (id, product_id, media_url, media_type, alt_text, display_order, is_primary)   VALUES ('9e8e3a39-feb5-41df-accf-5aa33fd8187d', '882ce05b-e671-4a77-9a2b-23ffc7d91138', 'SA042_main.jpg', 'image', 'Non-Catalog Brand Showcase Image 9', 8, false);
  INSERT INTO public.product_media (id, product_id, media_url, media_type, alt_text, display_order, is_primary)   VALUES ('3be2f57d-b8e6-4a3c-816a-85e611183342', '882ce05b-e671-4a77-9a2b-23ffc7d91138', 'SA045_main.jpg', 'image', 'Non-Catalog Brand Showcase Image 10', 9, false);
  INSERT INTO public.product_media (id, product_id, media_url, media_type, alt_text, display_order, is_primary)   VALUES ('36c55062-2bff-4257-93e3-a9b7740c7ec6', '882ce05b-e671-4a77-9a2b-23ffc7d91138', 'SA054_main.jpg', 'image', 'Non-Catalog Brand Showcase Image 11', 10, false);
  INSERT INTO public.product_media (id, product_id, media_url, media_type, alt_text, display_order, is_primary)   VALUES ('08ab3550-abc9-4da8-b544-a18bb32a7ac3', '882ce05b-e671-4a77-9a2b-23ffc7d91138', 'SA060_main.jpg', 'image', 'Non-Catalog Brand Showcase Image 12', 11, false);
  INSERT INTO public.product_media (id, product_id, media_url, media_type, alt_text, display_order, is_primary)   VALUES ('64e06139-42a8-4861-adff-23ebae7caa7c', '882ce05b-e671-4a77-9a2b-23ffc7d91138', 'SA061_main.jpg', 'image', 'Non-Catalog Brand Showcase Image 13', 12, false);

-- Mark featured products
UPDATE public.products SET is_featured = true WHERE id IN (SELECT id FROM public.products ORDER BY created_at DESC LIMIT 3);

-- =========================================================================
-- 3. INSERT SITE SETTINGS
-- =========================================================================
INSERT INTO public.site_settings (id, key, value, updated_at) VALUES ('01c3e3fe-9e00-4832-92e5-3de5c1bed418', 'site_status', '"live"'::jsonb, now());
INSERT INTO public.site_settings (id, key, value, updated_at) VALUES ('71345cda-29aa-4264-81e5-4e1d501bad2a', 'whatsapp_number', '"918421949875"'::jsonb, now());
INSERT INTO public.site_settings (id, key, value, updated_at) VALUES ('9449d54e-7618-4228-a5e4-d2c2e47bd196', 'homepage_banner', '{"title": "Kalaasutra by Shubham Art", "subtitle": "Handcrafted customized artwork, LED signboards, and premium nameplates for your special ones.", "image_url": "hero_bg.jpg"}'::jsonb, now());
INSERT INTO public.site_settings (id, key, value, updated_at) VALUES ('12d170a4-b541-4e22-adba-5063e42f0f86', 'active_theme', '"premium"'::jsonb, now());
INSERT INTO public.site_settings (id, key, value, updated_at) VALUES ('452ebf17-221a-4ea1-8990-973b14d504c1', 'delivery_message', '"Express delivery all over India. Handcrafted sketches shipped within 7-9 business days."'::jsonb, now());
INSERT INTO public.site_settings (id, key, value, updated_at) VALUES ('93cd1d97-dc24-4a5d-962d-95b6c193e15e', 'announcement_bar', '"\ud83c\udf89 Flat 10% Off on Anniversary & Birthday Portraits! Use code FESTIVE10 at checkout."'::jsonb, now());
INSERT INTO public.site_settings (id, key, value, updated_at) VALUES ('76fcd1cb-a96d-4b4e-8119-b0250c960fcb', 'payment_instructions', '"Kindly scan the UPI QR code or pay to mobile number +91 8421949875 (Shubham Sutar). Share your order number and transaction screenshot on WhatsApp to activate your order."'::jsonb, now());
INSERT INTO public.site_settings (id, key, value, updated_at) VALUES ('38b4dded-d694-4a54-9c11-617cb8af72e9', 'faq', '[{"question": "How do I place a custom order?", "answer": "Choose your product, click \"Customize Preview\" to enter details (names, styles, reference images), and click \"Order via WhatsApp\". The website will generate a pre-filled WhatsApp message. Once you send it, our artist will confirm details and share payment options."}, {"question": "Can I get my portrait framed?", "answer": "Yes! We offer options for premium Black Classic frames or Warm Wooden frames for physical deliveries. You can also opt for unframed rolled sketches or a high-resolution digital copy."}, {"question": "How long does delivery take?", "answer": "Since each artwork is hand-drawn and customized with precision, creation takes 3-5 days. Shipping takes another 3-4 days. Total delivery time is approximately 7-9 business days across India."}, {"question": "What are the payment modes?", "answer": "We support payments via UPI (GPay, PhonePe, Paytm) and direct bank transfers. You will need to share the payment screenshot on WhatsApp to finalize your order."}]'::jsonb, now());

-- =========================================================================
-- 4. INSERT OFFERS
-- =========================================================================
INSERT INTO public.offers (id, title, code, description, discount_type, discount_value, starts_at, ends_at, is_active, banner_image_url, applies_to, minimum_order_value, created_at, updated_at) VALUES ('3728e199-dcdf-4d92-973e-5c0a51c5d0dc', 'Festive Celebration Sale', 'FESTIVE10', 'Enjoy a flat 10% discount on all custom sketches and portrait orders.', 'percentage', 10.00, now(), now() + interval '90 days', true, 'festive_offer_banner.jpg', 'all_products', 499.00, now(), now());
INSERT INTO public.offers (id, title, code, description, discount_type, discount_value, starts_at, ends_at, is_active, banner_image_url, applies_to, minimum_order_value, created_at, updated_at) VALUES ('29460f6d-4fb3-4778-bddf-40e81903e861', 'Welcome First Order Discount', 'FIRST50', 'Get a flat ₹50 discount on your first order. Minimum purchase ₹299.', 'fixed_amount', 50.00, now(), now() + interval '365 days', true, 'welcome_offer_banner.jpg', 'all_products', 299.00, now(), now());

-- =========================================================================
-- 5. INSERT TESTIMONIALS
-- =========================================================================
INSERT INTO public.testimonials (id, customer_name, message, rating, source, is_visible, display_order, created_at) VALUES ('29d85afd-c9e3-4b87-b78f-d817f6949c14', 'Aarav Mehta', 'Ordered an anniversary A3 sketch frame for my wife. The details were incredible and looked exactly like the reference photo. She loved it! Fast shipping too.', 5, 'whatsapp', true, 0, now());
INSERT INTO public.testimonials (id, customer_name, message, rating, source, is_visible, display_order, created_at) VALUES ('e1efd509-ca86-4400-b8e1-17b5c4945c6a', 'Priya Deshmukh', 'The Acrylic LED Nameplate is of premium quality. The light is bright and the calligraphy font is gorgeous. Highly recommended for home decor!', 5, 'instagram', true, 0, now());
INSERT INTO public.testimonials (id, customer_name, message, rating, source, is_visible, display_order, created_at) VALUES ('3d8b57b5-1159-4519-a5a6-bcea84be282b', 'Rohan Joshi', 'Got a metal keychain with my name. Excellent build quality, and it feels heavy and premium. Truly value for money.', 4, 'instagram', true, 0, now());
INSERT INTO public.testimonials (id, customer_name, message, rating, source, is_visible, display_order, created_at) VALUES ('5930c95e-0d93-4f9b-b5c7-71590637300d', 'Neha Shinde', 'Amazing customer support! They kept me updated during the sketch creation and took my feedback positively before shipping.', 5, 'website', true, 0, now());

SET session_replication_role = origin;

COMMIT;